Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "10240"
      vb.cpus = 4
      vb.name = "k8s"
    end
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "./pb/main.yml"      
    end
  end
  